# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 04:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='document_briefing_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_briefing_note', to='applications.Record'),
        ),
        migrations.AddField(
            model_name='application',
            name='document_determination_approved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_determination_approved', to='applications.Record'),
        ),
        migrations.AddField(
            model_name='application',
            name='publish_determination_report',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='communication',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
