# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 04:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20170525_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 25, 12, 33, 28, 348258), verbose_name='Date'),
        ),
    ]
