# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20170530_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='routeid',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
