# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 02:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0004_auto_20170223_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('sent_date', models.DateField()),
                ('period', models.PositiveIntegerField(verbose_name='period (days)')),
                ('response_date', models.DateField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.Application')),
                ('documents', models.ManyToManyField(blank=True, to='applications.Document')),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='condition',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='applications.Referral'),
        ),
        migrations.AlterUniqueTogether(
            name='referral',
            unique_together=set([('application', 'referee')]),
        ),
    ]
