# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_auto_20170530_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='routeid',
            field=models.CharField(blank=True, default=1, max_length=4, null=True),
        ),
    ]
