# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_auto_20170224_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationPurpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('purpose', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='application',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='anchorage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='berth_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='beverage',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='application',
            name='brochures_itineries_adverts',
            field=models.ManyToManyField(blank=True, related_name='brochures_itineries_adverts', to='applications.Document'),
        ),
        migrations.AddField(
            model_name='application',
            name='byo_alcohol',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='application',
            name='cert_public_liability_insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cert_public_liability_insurace', to='applications.Document'),
        ),
        migrations.AddField(
            model_name='application',
            name='cert_survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cert_survey', to='applications.Document'),
        ),
        migrations.AddField(
            model_name='application',
            name='drop_off_pick_up',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='food',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='application',
            name='jetties',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='jetty_dot_approval',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='application',
            name='jetty_dot_approval_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='location_route_access',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_route_access', to='applications.Document'),
        ),
        migrations.AddField(
            model_name='application',
            name='max_participants',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='operating_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='other_supporting_docs',
            field=models.ManyToManyField(blank=True, related_name='other_supporting_docs', to='applications.Document'),
        ),
        migrations.AddField(
            model_name='application',
            name='proposed_location',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'On Land'), (1, 'On Water'), (2, 'Both')], null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='refuel_location_method',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='risk_mgmt_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_mgmt_plan', to='applications.Document'),
        ),
        migrations.AddField(
            model_name='application',
            name='safety_mgmt_procedures',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='safety_mgmt_plan', to='applications.Document'),
        ),
        migrations.AddField(
            model_name='application',
            name='sullage_disposal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='waste_disposal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='documents', to='applications.Document'),
        ),
        migrations.AlterField(
            model_name='application',
            name='vessels',
            field=models.ManyToManyField(blank=True, to='applications.Vessel'),
        ),
        migrations.AddField(
            model_name='application',
            name='purpose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.ApplicationPurpose'),
        ),
    ]
