# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_auto_20170530_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='approval_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_type',
            field=models.IntegerField(choices=[(1, 'Permit'), (2, 'Licence/permit'), (3, 'Part 5 - New Application'), (4, 'Emergency works'), (5, 'Part 5 - Amendment Request'), (6, 'Part 5 - Amendment Application'), (7, 'Test - Application')]),
        ),
    ]
