# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_auto_20170224_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='current_land_use',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='deed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deed', to='applications.Document'),
        ),
        migrations.AddField(
            model_name='application',
            name='land_owner_consent',
            field=models.ManyToManyField(blank=True, related_name='land_owner_consent', to='applications.Document'),
        ),
        migrations.AddField(
            model_name='application',
            name='river_reserve_lease',
            field=models.NullBooleanField(default=None),
        ),
    ]
