# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_auto_20170224_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='state',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'With admin'), (3, 'With referee')], default=1, editable=False),
        ),
    ]
