# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-13 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_applicationinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='comms_from',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='communication',
            name='comms_to',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='communication',
            name='comms_type',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Phone'), (2, 'Email'), (3, 'Mail')], default=0),
        ),
        migrations.AddField(
            model_name='communication',
            name='subject',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
