# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_auto_20170227_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='state',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'With admin'), (3, 'With referee'), (4, 'With assessor'), (5, 'With manager'), (6, 'Issued'), (7, 'Issued (with admin)'), (8, 'Declined')], default=1, editable=False),
        ),
    ]
