# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_auto_20170301_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='expire_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
