# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_referral_expire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='status',
            field=models.IntegerField(choices=[(1, 'Referred'), (2, 'Responded'), (3, 'Recalled'), (4, 'Expired')], default=1),
        ),
    ]
