# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-23 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_location_local_government_authority'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='supporting_info_demonstrate_compliance_trust_policies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporting_info_demonstrate_compliance_trust_policies', to='applications.Record'),
        ),
    ]
