# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 06:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0014_referral_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Requested'), (2, 'Approved'), (3, 'Returned')], default=1)),
                ('submit_date', models.DateField()),
                ('compliance', models.TextField(blank=True, help_text='Information to fulfil requirement of condition.', null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('approve_date', models.DateField(blank=True, null=True)),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compliance_applicant', to=settings.AUTH_USER_MODEL)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compliance_assignee', to=settings.AUTH_USER_MODEL)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applications.Condition')),
                ('documents', models.ManyToManyField(blank=True, to='applications.Document')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
