# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-23 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_application_supporting_info_demonstrate_compliance_trust_policies'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='vessel_or_craft_details',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
