# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-23 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_application_vessel_or_craft_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='other_relevant_documents',
            field=models.ManyToManyField(blank=True, related_name='other_relevant_documents', to='applications.Record'),
        ),
    ]
