# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_publicationfeedback_publicationnewspaper_publicationwebsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='certificate_dpd_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='certificate_folio',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='certificate_location',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='certificate_nearest_road_intersection',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='certificate_of_title_volume',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='certificate_reserve_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='certificate_street_number_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='certificate_subject_lot_lot_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='certificate_town_suburb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='deed_signed',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='application',
            name='landowner_consent_signed',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='application',
            name='proposed_development_cost',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='proposed_development_current_use_of_land',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='proposed_development_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='proposed_development_plans',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='application',
            name='river_lease_application_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='river_lease_proposed_development',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='application',
            name='river_lease_require_river_lease',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='application',
            name='river_lease_scan_of_application',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
