# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 07:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_auto_20170310_1254'),
        ('applications', '0016_auto_20170310_1026'),
    ]

    operations = [
    ]
