# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0017_merge_20170310_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='certificate_dpd_number',
        ),
        migrations.RemoveField(
            model_name='application',
            name='certificate_folio',
        ),
        migrations.RemoveField(
            model_name='application',
            name='certificate_location',
        ),
        migrations.RemoveField(
            model_name='application',
            name='certificate_nearest_road_intersection',
        ),
        migrations.RemoveField(
            model_name='application',
            name='certificate_of_title_volume',
        ),
        migrations.RemoveField(
            model_name='application',
            name='certificate_reserve_number',
        ),
        migrations.RemoveField(
            model_name='application',
            name='certificate_street_number_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='certificate_subject_lot_lot_number',
        ),
        migrations.RemoveField(
            model_name='application',
            name='certificate_town_suburb',
        ),
        migrations.RemoveField(
            model_name='application',
            name='deed_signed',
        ),
        migrations.RemoveField(
            model_name='application',
            name='landowner_consent_signed',
        ),
        migrations.AddField(
            model_name='application',
            name='document_completion',
            field=models.ManyToManyField(blank=True, related_name='document_completion', to='applications.Document'),
        ),
        migrations.AddField(
            model_name='application',
            name='document_determination',
            field=models.ManyToManyField(blank=True, related_name='document_determination', to='applications.Document'),
        ),
        migrations.AddField(
            model_name='application',
            name='document_draft',
            field=models.ManyToManyField(blank=True, related_name='document_draft', to='applications.Document'),
        ),
        migrations.AddField(
            model_name='application',
            name='document_final',
            field=models.ManyToManyField(blank=True, related_name='document_final', to='applications.Document'),
        ),
        migrations.AddField(
            model_name='location',
            name='dpd_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='folio',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='location',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='street_number_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='title_volume',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.RemoveField(
            model_name='application',
            name='proposed_development_plans',
        ),
        migrations.AddField(
            model_name='application',
            name='proposed_development_plans',
            field=models.ManyToManyField(blank=True, related_name='proposed_development_plans', to='applications.Document'),
        ),
        migrations.RemoveField(
            model_name='application',
            name='river_lease_scan_of_application',
        ),
        migrations.AddField(
            model_name='application',
            name='river_lease_scan_of_application',
            field=models.ManyToManyField(blank=True, related_name='river_lease_scan_of_application', to='applications.Document'),
        ),
        migrations.RemoveField(
            model_name='publicationnewspaper',
            name='documents',
        ),
        migrations.AddField(
            model_name='publicationnewspaper',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='newspaper', to='applications.Document'),
        ),
        migrations.RemoveField(
            model_name='publicationwebsite',
            name='original_document',
        ),
        migrations.AddField(
            model_name='publicationwebsite',
            name='original_document',
            field=models.ManyToManyField(blank=True, related_name='original_document', to='applications.Document'),
        ),
        migrations.RemoveField(
            model_name='publicationwebsite',
            name='published_document',
        ),
        migrations.AddField(
            model_name='publicationwebsite',
            name='published_document',
            field=models.ManyToManyField(blank=True, related_name='published_document', to='applications.Document'),
        ),
    ]
