# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0017_auto_20170630_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='apply_on_behalf_of',
            field=models.IntegerField(blank=True, choices=[(1, 'On Behalf of yourself'), (2, 'On Behalf of indivdual as somebody else (as an authorised agent)'), (3, 'On Behalf of a company as somebody else (as an authorised agent)')], null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Permit'), (2, 'Licence/permit'), (3, 'Part 5 - New Application'), (4, 'Emergency works'), (5, 'Part 5 - Amendment Request'), (6, 'Part 5 - Amendment Application'), (7, 'Test - Application'), (8, 'Amend Permit'), (9, 'Amend Licence'), (10, 'Renew Permit'), (11, 'Renew Licence')], null=True),
        ),
    ]
