# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0018_auto_20170313_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='proposed_development_cost',
        ),
    ]
