# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 04:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_merge_20170313_1101'),
        ('applications', '0019_remove_application_proposed_development_cost'),
    ]

    operations = [
    ]
