# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 06:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0020_merge_20170313_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='effective_to',
        ),
        migrations.RemoveField(
            model_name='applicationpurpose',
            name='effective_to',
        ),
        migrations.RemoveField(
            model_name='compliance',
            name='effective_to',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='effective_to',
        ),
        migrations.RemoveField(
            model_name='document',
            name='effective_to',
        ),
        migrations.RemoveField(
            model_name='location',
            name='effective_to',
        ),
        migrations.RemoveField(
            model_name='publicationfeedback',
            name='effective_to',
        ),
        migrations.RemoveField(
            model_name='publicationnewspaper',
            name='effective_to',
        ),
        migrations.RemoveField(
            model_name='publicationwebsite',
            name='effective_to',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='effective_to',
        ),
        migrations.RemoveField(
            model_name='task',
            name='effective_to',
        ),
        migrations.RemoveField(
            model_name='vessel',
            name='effective_to',
        ),
    ]
