# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-25 04:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0020_auto_20170724_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliance',
            name='app_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Permit'), (2, 'Licence/permit'), (3, 'Part 5 - New Application'), (4, 'Emergency works'), (5, 'Part 5 - Amendment Request'), (6, 'Part 5 - Amendment Application'), (7, 'Test - Application'), (8, 'Amend Permit'), (9, 'Amend Licence'), (10, 'Renew Permit'), (11, 'Renew Licence')], null=True),
        ),
        migrations.AddField(
            model_name='compliance',
            name='approval_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compliance',
            name='assessed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compliance_assigned_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliance',
            name='assessed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compliance',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compliance',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Due'), (3, 'Future'), (4, 'Approved'), (5, 'With Assessor'), (6, 'With Manager'), (7, 'With Licence Holder')], default=1),
        ),
        migrations.AlterField(
            model_name='compliance',
            name='submit_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
