# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0021_auto_20170313_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationfeedback',
            name='documents',
            field=models.FileField(upload_to=''),
        ),
    ]
