# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0021_auto_20170313_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='river_lease_proposed_development',
            new_name='river_lease_reserve_licence',
        ),
        migrations.RemoveField(
            model_name='application',
            name='current_land_use',
        ),
        migrations.RemoveField(
            model_name='application',
            name='proposed_development_description',
        ),
        migrations.RemoveField(
            model_name='application',
            name='river_reserve_lease',
        ),
        migrations.AlterField(
            model_name='vessel',
            name='engine',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='passenger_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='registration',
            field=models.ManyToManyField(blank=True, to='applications.Document'),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='vessel_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='vessel_type',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Vessel'), (1, 'Craft')], null=True),
        ),
    ]
