# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0022_auto_20170314_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='registration',
            field=models.ManyToManyField(blank=True, to='applications.Document'),
        ),
    ]
