# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0023_auto_20170314_1207'),
        ('applications', '0022_auto_20170315_1048'),
    ]

    operations = [
    ]
