# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0023_auto_20170320_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='status',
            field=models.IntegerField(choices=[(1, 'Proposed'), (2, 'Applied'), (3, 'Rejected'), (4, 'Cancelled')], default=1),
        ),
    ]
