# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0024_auto_20170321_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='application',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='task',
            name='documents',
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'Landowner consent'), (2, 'Deed'), (3, 'Assessment report'), (4, 'Referee response'), (5, 'Lodgement document'), (6, 'Draft document'), (7, 'Final document'), (8, 'Determination document'), (9, 'Completed document')], null=True),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
