# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 03:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0024_merge_20170315_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='river_lease_proposed_development',
            new_name='river_lease_reserve_licence',
        ),
    ]
