# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0025_auto_20170324_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='condition',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='condition',
            name='recur_freq',
            field=models.PositiveIntegerField(blank=True, help_text='How frequently is the recurrence pattern applied (e.g. every 2 months)', null=True, verbose_name='recurrence frequency'),
        ),
        migrations.AddField(
            model_name='condition',
            name='recur_pattern',
            field=models.IntegerField(blank=True, choices=[(1, 'Weekly'), (2, 'Monthly'), (3, 'Annually')], null=True),
        ),
    ]
