# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-06 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0025_organisationcontact_organisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationPending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('abn', models.CharField(blank=True, max_length=50, null=True, verbose_name='ABN')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Approved')], default=1)),
            ],
        ),
    ]
