# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-06 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20170602_1200'),
        ('applications', '0026_organisationpending'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationpending',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_pending_billing_address', to='accounts.Address'),
        ),
        migrations.AddField(
            model_name='organisationpending',
            name='postal_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_pending_postal_address', to='accounts.Address'),
        ),
    ]
