# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0026_auto_20170327_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicationfeedback',
            name='documents',
            field=models.FileField(upload_to=''),
        ),
    ]
