# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-06 08:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0027_auto_20170906_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationpending',
            name='email_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
