# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0027_auto_20170327_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='engine',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='engine (kW)'),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='passenger_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='size (m)'),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='vessel_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Vessel identification'),
        ),
    ]
