# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 04:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0029_application_proposed_development_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicationwebsite',
            name='original_document',
        ),
        migrations.AddField(
            model_name='publicationwebsite',
            name='original_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original_document', to='applications.Document'),
        ),
        migrations.RemoveField(
            model_name='publicationwebsite',
            name='published_document',
        ),
        migrations.AddField(
            model_name='publicationwebsite',
            name='published_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='published_document', to='applications.Document'),
        ),
    ]
