# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-07 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0029_auto_20170906_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationpending',
            name='company_exists',
            field=models.BooleanField(default=False),
        ),
    ]
