# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-07 06:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20170602_1200'),
        ('applications', '0030_organisationpending_company_exists'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationExtras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin1', models.CharField(blank=True, max_length=50, null=True)),
                ('pin2', models.CharField(blank=True, max_length=50, null=True)),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.Organisation')),
            ],
        ),
        migrations.AddField(
            model_name='organisationpending',
            name='identification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.Record'),
        ),
    ]
