# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0030_auto_20170331_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicationfeedback',
            name='documents',
        ),
        migrations.AddField(
            model_name='publicationfeedback',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='feedback', to='applications.Document'),
        ),
    ]
