# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-07 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0031_auto_20170907_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationextras',
            name='identification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.Record'),
        ),
    ]
