# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-11 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0032_organisationextras_identification'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationpending',
            name='submit_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
