# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0032_auto_20170406_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='routeid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
