# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0033_application_routeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='routeid',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
