# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-21 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0034_organisationpending_assignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationpending',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Declined')], default=1),
        ),
    ]
