# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0034_auto_20170407_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='assessment_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
