# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-21 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0035_auto_20170921_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationpending',
            name='pin1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organisationpending',
            name='pin2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='organisationextras',
            name='identification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisation_extras_org_identification', to='applications.Record'),
        ),
        migrations.AlterField(
            model_name='organisationextras',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organisation_extras_org_id', to='accounts.Organisation'),
        ),
    ]
