# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 06:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0035_application_assessment_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, null=True)),
                ('state', models.IntegerField()),
                ('created', models.DateTimeField(default=datetime.datetime(2017, 4, 19, 14, 45, 21, 877462), verbose_name='Date')),
            ],
        ),
        migrations.AlterField(
            model_name='application',
            name='state',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'With Admin Officer'), (3, 'With Referrals'), (4, 'With Assessor'), (5, 'With Manager'), (6, 'Issued'), (7, 'Issued (with admin)'), (8, 'Declined'), (9, 'New'), (10, 'Approved'), (11, 'Expired'), (12, 'With Director'), (13, 'With Exec')], default=1, editable=False),
        ),
        migrations.AddField(
            model_name='communication',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applications.Application'),
        ),
        migrations.AddField(
            model_name='communication',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='communication_docs', to='applications.Document'),
        ),
    ]
