# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 08:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0036_auto_20170419_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='state',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'With Admin Officer'), (3, 'With Referrals'), (4, 'With Assessor'), (5, 'With Manager'), (6, 'Issued'), (7, 'Issued (with admin)'), (8, 'Declined'), (9, 'New'), (10, 'Approved'), (11, 'Expired'), (12, 'With Director'), (13, 'With Executive'), (14, 'Completed')], default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='communication',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 20, 16, 19, 21, 434560), verbose_name='Date'),
        ),
    ]
