# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-02 08:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20170602_1200'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0036_auto_20170921_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comms_to', models.CharField(blank=True, max_length=256, null=True)),
                ('comms_from', models.CharField(blank=True, max_length=256, null=True)),
                ('subject', models.CharField(blank=True, max_length=256, null=True)),
                ('comms_type', models.IntegerField(choices=[(0, 'None'), (1, 'Phone'), (2, 'Email'), (3, 'Mail')], default=0)),
                ('details', models.TextField(blank=True, null=True)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('records', models.ManyToManyField(blank=True, related_name='account_communication_docs', to='applications.Record')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationOrganisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comms_to', models.CharField(blank=True, max_length=256, null=True)),
                ('comms_from', models.CharField(blank=True, max_length=256, null=True)),
                ('subject', models.CharField(blank=True, max_length=256, null=True)),
                ('comms_type', models.IntegerField(choices=[(0, 'None'), (1, 'Phone'), (2, 'Email'), (3, 'Mail')], default=0)),
                ('details', models.TextField(blank=True, null=True)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Organisation')),
                ('records', models.ManyToManyField(blank=True, related_name='org_communication_docs', to='applications.Record')),
            ],
        ),
    ]
