# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-04 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0037_communicationaccount_communicationorganisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='route_status',
            field=models.CharField(blank=True, default=1, max_length=256, null=True),
        ),
    ]
