# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 03:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('applications', '0037_auto_20170420_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_group_assignment', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 26, 11, 17, 21, 353084), verbose_name='Date'),
        ),
    ]
