# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-12 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0038_application_route_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='comms_type',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Phone'), (2, 'Email'), (3, 'Mail'), (4, 'System')], default=0),
        ),
    ]
