# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 04:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0038_auto_20170426_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='swan_river_trust_board_feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_swan_river_board_feedback', to='applications.Document'),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_type',
            field=models.IntegerField(choices=[(1, 'Permit'), (2, 'Licence/permit'), (3, 'Part 5 - New Application'), (4, 'Emergency works'), (5, 'Part 5 - Ammendment Request'), (6, 'Part 5 - Amendment Application')]),
        ),
        migrations.AlterField(
            model_name='communication',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 22, 12, 0, 14, 407722), verbose_name='Date'),
        ),
    ]
