# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-03 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0040_referral_proposed_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='sumbitter_comment',
            field=models.TextField(blank=True, default=1, max_length=256, null=True),
        ),
    ]
