# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 08:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0041_auto_20170522_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 22, 16, 2, 23, 203734), verbose_name='Date'),
        ),
    ]
