# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 09:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0042_auto_20170522_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='document_draft_signed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_draft_signed', to='applications.Document'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 22, 17, 5, 43, 929640), verbose_name='Date'),
        ),
    ]
