# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 04:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0043_auto_20170522_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='document_memo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_memo', to='applications.Document'),
        ),
        migrations.AddField(
            model_name='application',
            name='document_new_draft_v3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_newdraftv3', to='applications.Document'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 23, 12, 33, 20, 500259), verbose_name='Date'),
        ),
    ]
