# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-30 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0043_auto_20171114_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='liquor_licence',
            field=models.NullBooleanField(default=None),
        ),
    ]
