# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 08:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0045_auto_20170523_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='document_breifing_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_breifing_note', to='applications.Document'),
        ),
        migrations.AddField(
            model_name='application',
            name='document_determination_approved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_determination_approved', to='applications.Document'),
        ),
        migrations.AddField(
            model_name='application',
            name='publish_determination_report',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='communication',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 23, 16, 31, 24, 377513), verbose_name='Date'),
        ),
    ]
