# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-23 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0046_auto_20180119_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliance',
            name='status',
            field=models.IntegerField(choices=[(1, 'Current'), (2, 'Due'), (3, 'Future'), (4, 'Approved'), (5, 'With Assessor'), (6, 'With Manager'), (7, 'With Licence Holder'), (8, 'Overdue'), (9, 'Submitted')], default=3),
        ),
    ]
