# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-26 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('applications', '0049_auto_20180125_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliance',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_group_assignment', to='auth.Group'),
        ),
    ]
