# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-29 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0051_compliance_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliance',
            name='submit_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
