# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-31 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0053_compliance_submitted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='suspend',
            field=models.BooleanField(default=False),
        ),
    ]
