# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-02 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0054_condition_suspend'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='advise',
            field=models.TextField(blank=True, null=True),
        ),
    ]
