# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-26 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0056_stakeholdercomms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholdercomms',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='stakeholdercomms',
            name='role',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Applicant'), (2, 'Submitter'), (3, 'Referral'), (4, 'Feedback')], default=0),
        ),
    ]
