# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-26 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0057_auto_20180226_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholdercomms',
            name='comm_type',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Email'), (2, 'Posted')], default=0),
        ),
    ]
