# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-16 02:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0058_stakeholdercomms_comm_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='sumbitter_comment',
            new_name='submitter_comment',
        ),
    ]
