# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-23 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0059_auto_20180516_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionPredefined',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('condition', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0)),
            ],
        ),
    ]
