# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-05 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0061_auto_20180523_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='apply_on_behalf_of',
            field=models.IntegerField(blank=True, choices=[(1, 'On Behalf of yourself'), (2, 'On Behalf of your company / government agency'), (3, 'On Behalf of indivdual as somebody else (as an authorised agent)'), (4, 'On Behalf of a company as somebody else (as an authorised agent)'), (5, 'Internal')], null=True),
        ),
    ]
