# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address_emailuserprofile_organisation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailuserprofile',
            options={'verbose_name': 'user profile', 'verbose_name_plural': 'user profiles'},
        ),
        migrations.AlterField(
            model_name='address',
            name='line2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Line 2'),
        ),
        migrations.AlterField(
            model_name='address',
            name='locality',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Suburb / Town'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postcode',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
