# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170302_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.IntegerField(blank=True, choices=[(1, 'ACT'), (2, 'NSW'), (3, 'NT'), (4, 'QLD'), (5, 'SA'), (6, 'TAS'), (7, 'VIC'), (8, 'WA')], default=8, null=True),
        ),
        migrations.AlterField(
            model_name='emailuserprofile',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_billing_address', to='accounts.Address'),
        ),
        migrations.AlterField(
            model_name='emailuserprofile',
            name='postal_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_postal_address', to='accounts.Address'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_billing_address', to='accounts.Address'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='postal_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_postal_address', to='accounts.Address'),
        ),
    ]
