# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 03:24
from __future__ import unicode_literals

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Group = apps.get_model("auth", "Group")
    Group.objects.get_or_create(name='Approver')
    Group.objects.get_or_create(name='Assessor')
    Group.objects.get_or_create(name='Processor')
    Group.objects.get_or_create(name='Referee')


def reverse_func(apps, schema_editor):
    # No reverse function.
    return


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170302_1510'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
