# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 04:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_application_assessed_by'),
        ('approvals', '0004_auto_20170608_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='ammendment_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ammendment_application', to='applications.Application'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application', to='applications.Application'),
        ),
    ]
