# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-12 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0005_auto_20170609_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='cancellation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approval',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approval',
            name='reinstate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approval',
            name='surrender_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='status',
            field=models.IntegerField(choices=[(1, 'Current'), (2, 'Expired'), (3, 'Cancelled'), (4, 'Surrendered'), (5, 'Suspended'), (6, 'Reinstate')]),
        ),
    ]
