# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-24 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0007_auto_20170616_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='issue_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
