# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-12 05:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0010_communicationapproval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communicationapproval',
            name='application',
        ),
        migrations.AddField(
            model_name='communicationapproval',
            name='approval',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='approvals.Approval'),
            preserve_default=False,
        ),
    ]
